# Generated by Django 3.0.3 on 2020-02-20 01:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cow_say', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cowtext',
            name='date_submitted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
