# Generated by Django 3.0.3 on 2020-02-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow_say', '0002_cowtext_date_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cowtext',
            name='template',
            field=models.CharField(choices=[(None, 'cow'), ('beavis.zen', 'beavis.zen'), ('bong', 'bong'), ('bud-frogs', 'bud-frogs'), ('bunny', 'bunny'), ('calvin', 'calvin'), ('cheese', 'cheese'), ('cock', 'cock'), ('cower', 'cower'), ('daemon', 'daemon'), ('default\ndragon', 'default\ndragon'), ('dragon-and-cow', 'dragon-and-cow'), ('duck', 'duck'), ('elephant', 'elephant'), ('elephant-in-snake', 'elephant-in-snake'), ('eyes', 'eyes'), ('flaming-sheep\nghostbusters', 'flaming-sheep\nghostbusters'), ('gnu', 'gnu'), ('head-in', 'head-in'), ('hellokitty', 'hellokitty'), ('kiss', 'kiss'), ('kitty', 'kitty'), ('koala', 'koala'), ('kosh', 'kosh'), ('luke-koala\nmech-and-cow', 'luke-koala\nmech-and-cow'), ('meow', 'meow'), ('milk', 'milk'), ('moofasa', 'moofasa'), ('moose', 'moose'), ('mutilated', 'mutilated'), ('pony', 'pony'), ('pony-smaller', 'pony-smaller'), ('ren', 'ren'), ('sheep\nskeleton', 'sheep\nskeleton'), ('snowman', 'snowman'), ('sodomized-sheep', 'sodomized-sheep'), ('stegosaurus', 'stegosaurus'), ('stimpy', 'stimpy'), ('suse', 'suse'), ('three-eyes', 'three-eyes'), ('turkey\nturtle', 'turkey\nturtle'), ('tux', 'tux'), ('unipony', 'unipony'), ('unipony-smaller', 'unipony-smaller'), ('vader', 'vader'), ('vader-koala', 'vader-koala'), ('www\n', 'www\n')], max_length=26, null=True),
        ),
    ]
