# Generated by Django 3.0.3 on 2020-02-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow_say', '0003_cowtext_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowtext',
            name='template',
            field=models.CharField(blank=True, choices=[(None, 'cow'), ('apt', 'apt'), ('beavis.zen', 'beavis.zen'), ('bong', 'bong'), ('bud-frogs', 'bud-frogs'), ('bunny', 'bunny'), ('calvin', 'calvin'), ('cheese', 'cheese'), ('cock', 'cock'), ('cower', 'cower'), ('daemon', 'daemon'), ('default', 'default'), ('dragon', 'dragon'), ('dragon-and-cow', 'dragon-and-cow'), ('duck', 'duck'), ('elephant', 'elephant'), ('elephant-in-snake', 'elephant-in-snake'), ('eyes', 'eyes'), ('flaming-sheep', 'flaming-sheep'), ('ghostbusters', 'ghostbusters'), ('gnu', 'gnu'), ('head-in', 'head-in'), ('hellokitty', 'hellokitty'), ('kiss', 'kiss'), ('kitty', 'kitty'), ('koala', 'koala'), ('kosh', 'kosh'), ('luke-koala', 'luke-koala'), ('mech-and-cow', 'mech-and-cow'), ('meow', 'meow'), ('milk', 'milk'), ('moofasa', 'moofasa'), ('moose', 'moose'), ('mutilated', 'mutilated'), ('pony', 'pony'), ('pony-smaller', 'pony-smaller'), ('ren', 'ren'), ('sheep', 'sheep'), ('skeleton', 'skeleton'), ('snowman', 'snowman'), ('sodomized-sheep', 'sodomized-sheep'), ('stegosaurus', 'stegosaurus'), ('stimpy', 'stimpy'), ('suse', 'suse'), ('three-eyes', 'three-eyes'), ('turkey', 'turkey'), ('turtle', 'turtle'), ('tux', 'tux'), ('unipony', 'unipony'), ('unipony-smaller', 'unipony-smaller'), ('vader', 'vader'), ('vader-koala', 'vader-koala'), ('www', 'www'), ('', '')], max_length=26, null=True),
        ),
    ]
